### PR TITLE
Move to HSF training organisation #51

### PR DESCRIPTION
**Pull request by chrisburr**
This PR deletes all the files and adds a link to the new HSF organisation: https://github.com/hsf-training/analysis-essentials

If anyone **would like to join hsf-training and get merge privileges** ask me directly or react to this comment with a 🎉.

For the existing webpage I haven't set up redirects yet but the new repository deploys to the `gh-pages` in both repositories.

### CODE REVIEW

**Comment by vlisovsk** [comment]
Now, the question is how relevant is an explicit mentioning of the LHCb software in these lessons? Let's say if I open the first python lesson, I immediately see the discussion on the LHCb software (in)compatibility with python3. Should it be generalized?

**Comment by chrisburr** [comment]
Yes it should be. There is an issue about it on the new respository though I probably won’t have time to do it this week.

**Comment by chrisburr** [comment]
I've edited the settings to not require Travis to pass and make it possible to merge this. 😄

**Comment by eduardo-rodrigues** [comment]
One little question: what happens with the outstanding PRs? Do they get lost? Any way to try and accept as much as possible as soon as possible, and get that in in the new location?

**Comment by chrisburr** [comment]
There is only one commit missing so I can move that one over at some point.

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, just noticed this: how far are you from being able to close this?

**Comment by henryiii** [comment]
Can this be done? Both pages are active now, and it's really hard to even find the HSF one from here!

**Pull request merged**
