### PR TITLE
Getting the ball rolling

### PR DESCRIPTION
**Pull request by betatim**
Started a new repo for our computing essentials. Populated with things from `first-analysis-steps`, I think I got most of what is needed. It builds locally.

Who knows how to setup our friend travis?

### CODE REVIEW

**Comment by betatim** [comment]
(close ans re-open to wake up travis)

**Comment by betatim** [comment]
This is ready for reviewing and then merge.

**Comment by alexpearce** [comment]
But there are [70 files in the commit](https://github.com/lhcb/analysis-essentials/pull/1/files) :no_mouth: is there something specific you'd like checked?

**Comment by betatim** [comment]
Good point. Maybe we merge it when travis is happy? 70 files just to get the basics going :-(

I think I did the right thing in order for travis to push the build on merge.

**Comment by alexpearce** [comment]
Travis is happy, merge?

**Comment by betatim** [comment]
:+1:

**Pull request merged**
