### PR TITLE
Import git lesson and add CERN details

### PR DESCRIPTION
**Pull request by chrisburr**
Ignore this PR for now as it's still being actively worked on, just adding this PR so I can make a todo list.

- [x] Fix references
- [x] Move back to using master the panels plugin (lhcb/gitbook-plugin-panels#1)
- [x] Show off GitLab CI?
- [x] Set up SSH Keys

### CODE REVIEW

**Comment by chrisburr** [comment]
Okay @vbellee @dberzano @atrisovic @lbel, I think the git lesson is just about ready to review! Feel free to leave comments or make pull requests to to this branch. When teaching you don't have to follow this, but hopefully it's a start and gives something for non-particpants of the Starterkit to use.

 - To save you building it, I've put a preview of the full site here:
    http://chrisburr.me/git-lesson-preview
 - And you can find an example of the example "planets" repository here: 
    https://gitlab.cern.ch/cburr/planets/

@dberzano I know ALICE is officially using GitHub to some extent, do you think this lesson is sufficient? Or should anything else be added?

**Comment by alexpearce** [comment]
Would be good to get feedback from the other teachers of these lessons, but things look pretty swell to me.

You've done a really fantastic job @cburr, nice work 👍 💯

**Comment by chrisburr** [comment]
I suggest we give @dberzano, @atrisovic and @lbel until the end of today (unless they say they need longer)? If anything else needs modifying there can be another PR.

**Comment by dberzano** [comment]
Hi @chrisburr I have just came back from surgery and one of our Python experts (@mconcas) is coming back from a school, our plan is to have a look at the full material today and tomorrow, do you mind? (I know... sorry...)

Just for clarification, you sent us the following pointers to the material:

* **https://github.com/lhcb/analysis-essentials ← this is the one and only place where our lessons are supposed to be, right?**
* https://github.com/lhcb/starterkit-lessons (I believe this is LHCb-centric)
* https://github.com/lhcb/starterkit (source for [this webpage](https://lhcb.github.io/starterkit/))

**Comment by chrisburr** [comment]
Yes I think those urls represent everything and I'm happy to give you time to review the material and leave comments.

**Comment by dberzano** [comment]
As separately written in an email - do you intend to import [Software Carpentry's material](https://software-carpentry.org) or this repo is just "addenda" to it?

**Comment by chrisburr** [comment]
I was just replying but I'll post it here instead.

- **Git:** Fully imported from SC in this PR with various changes and additions.
- **Python:** I think @alexpearce and @gdujany have written this independently of SC. It would be nice to add more HEP specific material but this will probably need to happen over the next few Starterkits.
- **Bash:** I haven't had time to import the bash lesson and in any case I'm not sure how much there is to add (unlike git and python) so I'm happy to keep it as a reference to their [shell-novice lesson](https://swcarpentry.github.io/shell-novice/).

**Comment by dberzano** [comment]
@chrisburr you mention submodules in your checklist. Do you (as in LHCb) use them? We found them to be rather confusing for our users. If you don't use them, I propose we just don't mention them at all, maybe (or confine them to an "advanced topics" section).

**Comment by chrisburr** [comment]
@dberzano LHCb doesn't use them for core software. I considered adding them due to [this challenge](https://chrisburr.me/git-lesson-preview/git/03-create.html#places-to-create-git-repositories), but I agree that it is too advanced to cover here.

**Comment by dberzano** [comment]
Hi all, I have made a PR with some minor changes, please have a look at it. I have some general points:

* **ALICE mainly uses GitHub as it was pointed out.** We have a [dedicated documentation](https://alisw.github.io/git-tutorial/) (with an [advanced section too](https://alisw.github.io/git-advanced/)) which is quite ALICE-centric, but the part on opening Pull Requests still stands. We will also have a dedicated GitHub session during the ALICE-only days.
* **I think it's useful in all cases to teach CERN GitLab to ALICE people too.** Leaving aside the [detrimental effects it can have on your mental health when it does not work](https://cern.service-now.com/service-portal/view-outage.do?from=CSP-Service-Status-Board&n=OTG0040391) (and this is - by the way - the reason why we use GitHub), having private repositories for _e.g._ papers or unreleased analysis code without paying a fee is a big advantage.

The only major remark I have is: I am in utter disagreement with the collaboration workflow you illustrate (_i.e._ giving permissions to a repo as opposed to using merge/pull requests). Last year we have migrated 200+ active users from "plain Git" to GitHub, with Pull Requests, and what we are seeing is that:

* People appreciate reviewing and discussing changes instead of directly pushing code upstream. See a controversial one for instance: alisw/AliRoot#344.
* You can add automatic tests and _prevent_ code that does not pass testing to be merged in the first place. This means that "master will always work" (at least in most cases).

Given we can assume most of our audience never heard of Git before, it would be much much better if we taught them the Right Thing™ in the first place (_i.e._ fork, push to your fork, open a pull request, discuss, merge/close).

There's also a social aspect not to be neglected: our users now know that their code will be (mostly) read and judged by someone and they tend to be more attentive and respectful about it.

In practice it's true that merge/pull requests are "more complicated" but the advantages in most cases are outstanding, and if people understand and benefit from that, they won't complain about the additional interaction required.

So what I propose (me and/or @puccio are volunteering!) is to restructure the "Collaborating" section by adding how to write and deal with a Merge Request as the _main_ way to collaborate in modern Git.

What do you think?

**Comment by chrisburr** [comment]
> So what I propose (me and/or @puccio are volunteering!) is to restructure the "Collaborating" section by adding how to write and deal with a Merge Request as the main way to collaborate in modern Git.

I completely agree, if you can restructure it accordingly that would be great 👍 I think the repository name will need to be made unique for each person so that they are able to create forks.

**Comment by dberzano** [comment]
> I completely agree, if you can restructure it accordingly that would be great 👍 I think the repository name will need to be made unique for each person so that they are able to create forks.

Good point, let me start working on that!

**Comment by dberzano** [comment]
Done in chrisburr/analysis-essentials#2.

**Comment by dberzano** [comment]
H @chrisburr can chrisburr/analysis-essentials#2 be merged and can this PR be rebased, if you agree? There is agreement between ALICE people on it 👍

**Comment by chrisburr** [comment]
@dberzano Can you merge (or object to) dberzano/analysis-essentials#1 first?

(Sorry I was flying at the time so it was easier to make a PR to apply my suggestions than wait and copy them to the GitHub review interface)

**Pull request merged**
