### PR TITLE
Import shell lesson

### PR DESCRIPTION
**Pull request by chrisburr**
@dberzano I've started importing the `shell-novice` lesson if it's useful. If you'd rather do this a different way I'm happy to just close this PR without merging as it's only the SWC lesson with a little sed/perl processing at the moment.

If you do decide to look at making changes let me know so we can coordinate what we do.

### CODE REVIEW

**Comment by dberzano** [comment]
OK I am connected, I'll let you know!

**Comment by dberzano** [comment]
It seems you have already imported everything from [here](http://swcarpentry.github.io/shell-novice/): let me proof-read then! (And many thanks!)

**Comment by dberzano** [comment]
What is the convention we should use for section titles? I have previously used `##` ("h2") but I see that `###` ("h3") are used here.

**Comment by chrisburr** [comment]
If we have used `h2` elsewhere this should follow that convention. The only reason `h3` is used here is because it was used in the upstream shell-novice repository. (Plus it's logical!)

Does ALICE have a policy on which shell(s) people should use? I'm thinking of adding a section encouraging everyone to use bash unless they are comfortable taking on the burden of running a non-standard configuration.

**Comment by dberzano** [comment]
OK thanks for the clarification.

We do not recommend any particular shell (our environment script actually supports a wide variety of them), but I would recommend either bash or zsh.

The standard for our scripts is bash (beware, not POSIX).

So I would recommend bash.

**Comment by dberzano** [comment]
I would merge this PR as it is and open new ones for further fixes, corrections, improvements, what do you think?

**Comment by chrisburr** [comment]
Agreed! 👍

**Comment by dberzano** [comment]
Travis failed as the branch was removed when running, not a big deal.

**Pull request merged**
